AssertionError
AssertionError: View function mapping is overwriting an existing endpoint function: api_aggregated_data

Traceback (most recent call last)
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask_socketio/__init__.py", line 43, in __call__
return super(_SocketIOMiddleware, self).__call__(environ,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/engineio/middleware.py", line 74, in __call__
return self.wsgi_app(environ, start_response)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/app.py", line 2532, in wsgi_app
response = self.handle_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/app.py", line 688, in manual_scrape
scheduled_scrape()
^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/app.py", line 202, in scheduled_scrape
from aggregated_data import AggregatedData
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/aggregated_data.py", line 8, in <module>
from app import db, StoreStatus, cache
File "/root/M-S-A/app.py", line 872, in <module>
@app.route('/api/aggregated')
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/scaffold.py", line 449, in decorator
self.add_url_rule(rule, endpoint, f, **options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/scaffold.py", line 50, in wrapper_func
return f(self, *args, **kwargs)
       ^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/M-S-A/venv/lib/python3.12/site-packages/flask/app.py", line 1361, in add_url_rule
raise AssertionError(
^
AssertionError: View function mapping is overwriting an existing endpoint function: api_aggregated_data
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it.

